In [2]:
import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0x364A_23F2)
N = 500
n = 10
X = np.random.uniform(low=-1, high=1, size=(N, n))
y = np.zeros(N)

_c = np.random.randn(n)
_d = np.random.randn(n)

#We generate data as gaussians with mean and variance dependent on the feature x.
for i in range(N):
    y[i] = np.random.normal(loc=_c.T @ X[i], scale=abs(_d.T @ X[i]))


In [3]:
def phi(j,u):
    return (1/2)*cp.abs(u)+((1/2)-((j+1)/10))*u

In [4]:
v=cp.Variable((9,1))
teta =cp.Variable((9,n))

obj = cp.Minimize(cp.sum(cp.vstack([cp.sum(cp.vstack([phi(i,v[i]-teta[i,:]* X[t,:]-y[t]) for i in range(9)]))for t in range(0,N)])))
cons = [cp.norm(teta[i+1,:]-teta[i,:],1)<=v[i+1]-v[i] for i in range(8)]



c:\Users\Latitude 5289 2-in-1\AppData\Local\Programs\Python\Python310\lib\site-packages\cvxpy\expressions\expression.py:612: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 1 times so far.

  warnings.warn(msg, UserWarning)
c:\Users\Latitude 5289 2-in-1\AppData\Local\Programs\Python\Python310\lib\site-packages\cvxpy\expressions\expression.py:612: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code

In [12]:
cons

[Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ())),
 Inequality(Expression(CONVEX, NONNEGATIVE, ()))]

In [5]:
prom =cp.Problem(obj,cons)
result = prom.solve()

c:\Users\Latitude 5289 2-in-1\AppData\Local\Programs\Python\Python310\lib\site-packages\cvxpy\problems\problem.py:155: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "


In [6]:
result,v.value,teta.value

(3129.321102469284,
 array([[-2.64639137],
        [-1.34229561],
        [-0.69946972],
        [-0.30496747],
        [-0.02012715],
        [ 0.29587617],
        [ 0.86645247],
        [ 1.48435998],
        [ 2.68792298]]),
 array([[-0.34282921,  1.96368959,  1.20296763, -0.06182749, -1.14701681,
          0.20182779,  0.08099914, -1.47574762, -0.26975849, -1.21092238],
        [-0.13288463,  1.96368959,  1.06440766, -0.05037726, -0.91276959,
          0.20182779,  0.08099914, -0.82129114, -0.21432121, -1.21092238],
        [-0.13288463,  2.09508341,  1.06440766, -0.05037726, -0.69870216,
          0.11972901,  0.08099914, -0.71170295, -0.10864354, -1.21092238],
        [-0.13288463,  2.09508341,  1.01041577,  0.10956219, -0.67863102,
          0.01390472,  0.08099914, -0.65702747, -0.10864354, -1.21092238],
        [-0.13288463,  2.09508341,  1.01041577,  0.10956219, -0.56630435,
          0.01390472,  0.08394327, -0.48745796, -0.10864354, -1.21092238],
        [-0.10394112,  2.0

C________


In [7]:
prom_no_cons = cp.Problem(obj,)
result_n = prom_no_cons.solve()

In [10]:
v_hat=v.value
teta_hat=teta.value
result_n,v_hat,teta_hat

(3122.4294751964862,
 array([[-2.54413669],
        [-1.34728588],
        [-0.74604442],
        [-0.27686327],
        [-0.03760847],
        [ 0.25808255],
        [ 0.88644751],
        [ 1.48845713],
        [ 2.71852354]]),
 array([[-0.53330889,  1.77468807,  1.31942949, -0.1528987 , -1.44823285,
          0.13765922,  0.17844532, -1.54278969, -0.09559465, -1.06927663],
        [-0.35740281,  2.08024352,  0.97944495, -0.33558162, -1.03277282,
          0.43235102,  0.00942871, -0.9114148 , -0.40140307, -1.21524612],
        [-0.27156537,  2.14785875,  1.0295089 , -0.13934771, -0.78220274,
          0.18424712,  0.10943343, -0.82680584, -0.12305094, -1.18767862],
        [-0.09176385,  2.15033977,  0.98603792,  0.21861897, -0.62529724,
         -0.04007838,  0.02380229, -0.60070024, -0.11188525, -1.31280042],
        [-0.05411403,  2.19738785,  1.00283511,  0.16287044, -0.53945792,
         -0.00785163,  0.1303756 , -0.47831338, -0.08877199, -1.27779563],
        [-0.1250679 ,  2.

In [28]:
q_hat = v_hat+teta_hat@X.T
q_hat.shape,q_hat[:,200]

((9, 500),
 array([-4.64175765, -2.23432485, -1.54814134, -0.79168945, -0.38880599,
        -0.12857613,  0.97710725,  1.60723878,  1.83148791]))

In [39]:
xx =np.ediff1d(v_hat) - np.linalg.norm(np.diff(teta_hat, axis=0), 1, 1)
index_max= np.argmin(xx)
x_star = -np.sign(teta_hat[index_max+1] - teta_hat[index_max])
print(x_star)
# Verify that x_viol violates consistency (i.e. q_{i+1} - q_i < 0 for some i)
q_star = v_hat + teta_hat @ x_star
print(f"\n bishtarin meghdar ekhtelaph: {np.min(np.diff(q_viol))}")

[-1. -1.  1.  1. -1. -1.  1. -1.  1.  1.]

 bishtarin meghdar ekhtelaph: -2.9664502347810986


In [38]:
teta_hat@x_viol+v_hat.T

array([[-0.75204772, -2.52164714, -1.50871128, -1.26558984, -1.22574583,
        -0.79671154, -0.06232211,  0.12863224,  1.84041697]])